// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: list.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getListsByUserId = `-- name: GetListsByUserId :many
SELECT li.id, li.list_id, li.name, li.qty, li.unit, li.price, li.created_at, li.updated_at, l.name AS list_name, l.frequency, l.target_date, l.updated_at AS list_updated_at
FROM list_items li
JOIN list l ON li.list_id = l.id
WHERE l.user_id = $1
ORDER BY l.updated_at DESC
`

type GetListsByUserIdRow struct {
	ID            int64
	ListID        uuid.UUID
	Name          string
	Qty           sql.NullInt16
	Unit          sql.NullString
	Price         sql.NullInt16
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	ListName      string
	Frequency     sql.NullString
	TargetDate    sql.NullTime
	ListUpdatedAt sql.NullTime
}

func (q *Queries) GetListsByUserId(ctx context.Context, userID uuid.UUID) ([]GetListsByUserIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getListsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetListsByUserIdRow
	for rows.Next() {
		var i GetListsByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.Name,
			&i.Qty,
			&i.Unit,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ListName,
			&i.Frequency,
			&i.TargetDate,
			&i.ListUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
