// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Catalog struct {
	ID         int16
	Name       string
	CategoryID int16
	UpdatedAt  sql.NullTime
}

type Category struct {
	ID   int16
	Name string
	Icon sql.NullString
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
	IsActive       bool
	FirstName      string
	LastName       string
}
