// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Catalog struct {
	ID         int16
	Name       string
	CategoryID int16
	UpdatedAt  sql.NullTime
}

type Category struct {
	ID   int16
	Name string
	Icon sql.NullString
}

type List struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	Frequency  sql.NullString
	TargetDate sql.NullTime
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type ListItem struct {
	ID        int64
	ListID    uuid.UUID
	Name      string
	Qty       sql.NullInt16
	Unit      sql.NullString
	Price     sql.NullInt16
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
	IsActive       bool
	FirstName      string
	LastName       string
}
