-- +goose Up
CREATE TABLE catalog(
    id SMALLINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name CITEXT not null UNIQUE,
    category_id SMALLINT not null references category(id) on update cascade on delete restrict,
    updated_at timestamptz DEFAULT now()
);

CREATE INDEX idx_catalog_category_id ON catalog(category_id);

-- +goose Down
DROP TABLE catalog;
